class Commands:
    LEECH = "2leech"
    PURGE = "2purge"
    PAUSEALL = "2pauseall"
    RESUMEALL = "2resumeall"
    STATUS = "2status"
    SETTINGS = "2settings"
    EXEC = "2exec"
    UPLOAD = "2upload"
    YTDL = "2ytdl"
    PYTDL = "2pytdl"
    ABOUT = "2about"
    GETLOGS = "2getlogs"
    SERVER = "2server"
    USERSETTINGS = "2usetting"
